### ISSUE TITLE
failed compile the virtual camera application

### ISSUE THREAD

**Issue by PK15946** [gabrieleilertsen/hdrcnn#11]
Hi,

Thanks for your impressive job! It works as good as shown in the paper wih my own images.

But now I want to train the net and suffering errors when executing "gcc -Wall -lm -lstdc++ -lopencv_core -lopencv_imgproc -lopencv_imgcodecs virtualcamera.cpp -o virtualcamera"

The error shown is that"virtualcamera.cpp:314:57: error: no match for ‘operator+’ (operand types are ‘cv::Mat’ and ‘cv::Vec<double, 4>’)
                 host_roi = host_roi.mul(1.0 / (host_roi + sigmoid_a*Scalar(1,1,1)));
                                                ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
"
Do you have any idea, or could you please tell me the versions of gcc and opencv you are using? Thanks in advance!

**Comment by musicrainie** [comment]
Try "gcc virtualcamera.cpp -o virtualcamera -lm -lstdc++ -lopencv_core -lopencv_imgproc -lopencv_imgcodecs -std=c++11". 
My setting: Ubuntu16.04, gcc5.4, OpenCv3.4.1

**Comment by PK15946** [comment]
THANK YOU! @musicrainie , it works like a charm!!!!

**Comment by cherryMo** [comment]
@PK15946 
Hi， It  works bad with my own images. 
[https://github.com/gabrieleilertsen/hdrcnn/issues/12 ](url)    this is one of my own image.
can you give me some suggestions?

**Comment by PK15946** [comment]
Hi, @musicrainie @gabrieleilertsen  I have successfully compiled the virtual camera with the above script. However, the processed images in the 'training_data/jpg' all look blue and white like ./media/wgt/62A85AB0A85A8309/singlehdrcode/hdrcnn-master/training_data/jpg/im_000001_000001.jpg
/media/wgt/62A85AB0A85A8309/singlehdrcode/hdrcnn-master/training_data/jpg/im_000001_000002.jpg
/media/wgt/62A85AB0A85A8309/singlehdrcode/hdrcnn-master/training_data/jpg/im_000001_000003.jpg
/media/wgt/62A85AB0A85A8309/singlehdrcode/hdrcnn-master/training_data/jpg/im_000001_000004.jpg
are they right?

**Comment by PK15946** [comment]
Hi, @musicrainie @gabrieleilertsen I have successfully compiled the virtual camera with the above script. However, the processed images in the 'training_data/jpg' all look blue and white like 
![im_000001_000001](https://user-images.githubusercontent.com/34185974/43176926-7feff410-8ff8-11e8-81c7-d05a9ddcba15.jpg)
![im_000001_000002](https://user-images.githubusercontent.com/34185974/43176927-8021e0e2-8ff8-11e8-9a70-2f2b02a913e9.jpg)
![im_000001_000003](https://user-images.githubusercontent.com/34185974/43176928-8052a920-8ff8-11e8-847d-c8a5c3729c0d.jpg)
![im_000001_000004](https://user-images.githubusercontent.com/34185974/43176929-80836a42-8ff8-11e8-8b77-f8805b216936.jpg)



are they right?

**Comment by gabrieleilertsen** [comment]
No, that is not correct. The output images should be natural conventional images. Is it the same problem with the EXR ground truth images that are saved to disc? If not, the problem must be in the jpg output, and thus with the linked libjpeg library. Can you load and save an jpg as expected using OpenCV?

**Comment by PK15946** [comment]
Thanks for you reply. @gabrieleilertsen . 

When you say check the EXR ground truth that are saved to disc, do you mean those .bin files that are saved in "training_data/bin"? I read those .bin files use numpy.fromfile and save them to jpg format use scipy.misc.toimage, the results are correct.

Then I try to load and save a jpg using OpenCV using `#include "opencv2/opencv.hpp"

using namespace cv;
using namespace std;
int main(int argc, char *argv[])
{
Mat host_im;
host_im = cv::imread("1.jpg", CV_LOAD_IMAGE_COLOR|CV_LOAD_IMAGE_ANYDEPTH);
imwrite("45.jpg",host_im);
}` ,that result is correct, too.

**Comment by gabrieleilertsen** [comment]
Yes, I meant the raw binary HDR images. Forgot that those were not stored as EXR.

So, the problem must then be somewhere between generating the HDR output and converting this to an LDR an storing to disc. There are two operations in-between; first, a [camera response function is applied](https://github.com/gabrieleilertsen/hdrcnn/blob/ae7d22146299ea3776aa6ad1edca0ad80743f5b5/training_code/virtualcamera/virtualcamera.cpp#L310), and then the result is [converted to 8 bit and stored with a random compression quality](https://github.com/gabrieleilertsen/hdrcnn/blob/ae7d22146299ea3776aa6ad1edca0ad80743f5b5/training_code/virtualcamera/virtualcamera.cpp#L181). I can't figure out what your problem is, but I would suggest trying to look at those operations. For example, you can try to save the LDR image before applying the camera response function and see if this fixes the problem with the colors (the contrast will be exaggerated though). Or you can test if the problem is in the conversion and 8-bit storage. For example, there is a [conversion BGR2RGB](https://github.com/gabrieleilertsen/hdrcnn/blob/ae7d22146299ea3776aa6ad1edca0ad80743f5b5/training_code/virtualcamera/virtualcamera.cpp#L183). Is this causing the problem (seems from the examples above though, that the problem is more than simply swapped color channels)?

The question is what in your configuration is different. I have not experienced this problem myself. Seems a bit odd that a difference in configuration can generate such different output, and I haven't of anyone else having this problem. What version of OpenCV are you using?

**Comment by PK15946** [comment]
Really thanks for your kindly suggestion and guidance. @gabrieleilertsen  I guess I do have configuration problem in my computer(though I have no idea what could it be), since I try the code on another one and it works well... Both of that two computer with OpenCV 3.4.1 installed.
