### ISSUE TITLE
Could you pleased provided the full HDR dataset used in your work?

### ISSUE THREAD

**Issue by MudeLin** [gabrieleilertsen/hdrcnn#15]

**Comment by gabrieleilertsen** [comment]
Hi. I want to avoid to share the data, since there might be different types of copyright that I want to be sure not to violate. The sources are listed in [this document](http://hdrv.org/hdrcnn/material/sga17_supplementary.pdf). I guess some are not available anymore, but there should be many HDR resources available online.
