### ISSUE TITLE
About studying your model on HDR reconstruction 

### ISSUE THREAD

**Issue by JackSnowWolf** [gabrieleilertsen/hdrcnn#16]
We are a group of students from SJTU, and we want to do a HDR video reconstruction project based on your model. I do hope that you can give our permission to use your code. Of course, we do not have any commerical purpose.

As for the project, I am curious about your pretrain model weights. In your paper, you did provide a final model weights and vgg16 weights. Could you post your pretrain model weights so that we can compare results in different stages. Furthermore, what is the specific dateset used in your fine tune stage? 
It would be helpful if you can help us!

Sinerely,
Jack

**Comment by gabrieleilertsen** [comment]
Hi Jack. Of course, feel free to use the code for your project!

I think I found the correct pre-trained weights, that use the Places dataset. You can find them [here](http://hdrv.org/hdrcnn/material/hdrcnn_params_places.npz).

The HDR dataset used for the final training of the network is listed in the [supplementary document](http://hdrv.org/hdrcnn/material/sga17_supplementary.pdf). I have decided not to share the dataset directly, since I want to avoid violating potential copyrights. However, from the list of resources in the supplementary document, you should be able to gather your own dataset. Some resources may not be available anymore, but there should also be more resources available that are not listed in the document and which were not available at that time.

Good luck with your project!

**Comment by JackSnowWolf** [comment]
Thank you very much about your support ~
