### ISSUE TITLE
How to get jpg images?

### ISSUE THREAD

**Issue by Jee-King** [gabrieleilertsen/hdrcnn#2]
I wonder how exchange reconstruction HDR image from .exr to .jpg.  Could you share your scripts? Thank you very much!!

**Comment by Mhaiyang** [comment]
I also have the same problem.

**Comment by gabrieleilertsen** [comment]
Hi! I'm not sure if I understand correctly, but if you output the reconstructed images to JPG you do not get HDR images (unless you mean JPEG XT). The images will be clipped. There are also PNG images that are written when running the reconstruction. These are LDR images with decreased exposure, that are provided in order to give a fast visual comparison between input and reconstruction.

You can always change the output behavior in the I/O functions in 'img_io.py', if you prefer some other format.
