### ISSUE TITLE
convert sdr video to hdr10 video.

### ISSUE THREAD

**Issue by liulizhou** [gabrieleilertsen/hdrcnn#27]
Hi, @gabrieleilertsen 
I want to convert sdr video to hdr10 video using DL. I have some questions about datasets. 
* I extract hdr frame from hdr10 video using following command based ffmpeg.
```bash
ffmpeg -i input_hdr10.mkv -vf "select=not(mod(n\,50))" -vsync vfr -pix_fmt yuv420p10le -f rawvideo output.gbr
```
It means extracting one frame every 50 frames and saving to raw rgb format (maybe ffmpeg convert yuv420p10le to RGB). I extract sdr frames in the same way. Then I get thoundsands of sdr and hdr10 paired dataset and is it right regard them as the training data?  or should i do ```eo2100``` transfer function to make non-linear hdr10 to linear signals as the training data?
please give me some suggestions about convert sdr video to hdr10 video if possibly. e.g datasets or others. thanks.
* How can you extract hdr video to .exr file ?

**Comment by gabrieleilertsen** [comment]
Yes, images should be linearized. The training code uses OpenCV to read images, and a suitable format is EXR, so OpenCV need to be compiled with OpenEXR. I'm not sure on the easiest way of converting HDR video to EXR, maybe you have to use some intermediate format before converting to EXR.

**Comment by chencuber** [comment]
> Hi, @gabrieleilertsen
> I want to convert sdr video to hdr10 video using DL. I have some questions about datasets.
> 
> * I extract hdr frame from hdr10 video using following command based ffmpeg.
> 
> ```shell
> ffmpeg -i input_hdr10.mkv -vf "select=not(mod(n\,50))" -vsync vfr -pix_fmt yuv420p10le -f rawvideo output.gbr
> ```
> 
> It means extracting one frame every 50 frames and saving to raw rgb format (maybe ffmpeg convert yuv420p10le to RGB). I extract sdr frames in the same way. Then I get thoundsands of sdr and hdr10 paired dataset and is it right regard them as the training data? or should i do `eo2100` transfer function to make non-linear hdr10 to linear signals as the training data?
> please give me some suggestions about convert sdr video to hdr10 video if possibly. e.g datasets or others. thanks.
> 
> * How can you extract hdr video to .exr file ?

hi，@liulizhou，
what about color space problem, since sdr image seems follows bt.709, while hdr image is usually bt.2020. Do you find some easier way to construct dataset? I also want to know how to extact hdr video to exr file directly.

**Comment by PedestrianZQZ** [comment]
> > Hi, @gabrieleilertsen
> > I want to convert sdr video to hdr10 video using DL. I have some questions about datasets.
> > 
> > * I extract hdr frame from hdr10 video using following command based ffmpeg.
> > 
> > ```shell
> > ffmpeg -i input_hdr10.mkv -vf "select=not(mod(n\,50))" -vsync vfr -pix_fmt yuv420p10le -f rawvideo output.gbr
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It means extracting one frame every 50 frames and saving to raw rgb format (maybe ffmpeg convert yuv420p10le to RGB). I extract sdr frames in the same way. Then I get thoundsands of sdr and hdr10 paired dataset and is it right regard them as the training data? or should i do `eo2100` transfer function to make non-linear hdr10 to linear signals as the training data?
> > please give me some suggestions about convert sdr video to hdr10 video if possibly. e.g datasets or others. thanks.
> > 
> > * How can you extract hdr video to .exr file ?
> 
> hi，@liulizhou，
> what about color space problem, since sdr image seems follows bt.709, while hdr image is usually bt.2020. Do you find some easier way to construct dataset? I also want to know how to extact hdr video to exr file directly.

hi, @chencuber ,
i encounter same problem and want to know how to extract hdr video to exr file, did you solved it?

**Comment by RonRicoSuave** [comment]
@PedestrianZQZ @liulizhou it's more ghetto than using this project, but if your device supports DolbyVision profile 8, you can use  [dovi_tool](https://github.com/quietvoid/dovi_tool)'s new capability of generating dolby metadata from MadVR [measurement file](http://web.archive.org/web/20201111214723/http://madshi.net/madVRhdrMeasure78.zip) of plain HDR10 and a non-graded SDR source converted to that to get something that ends up coming close without needing to upscale or do anything slower than an encode to HEVC with some colorspace conversion.   I'm getting good results on everything I've tried it on so far.   Rec. 709 4:2:0 subsampled chroma ends up with slightly brighter colors when transformed into BT.2020, but subsampled chroma is trash so don't expect miracles in that department.   You'll need ffmpeg and tsmuxer as well, google will find them for you:

NPL can be played with to get various output levels but 300 seems to work well. 

Notes follow:

`ffmpeg -hide_banner -loglevel error -i "sdr_source.ext" ^ 
-vf format=gbrpf32le,zscale=pin=709:tin=709:min=709:p=2020:m=2020_ncl:t=smpte2084:npl=300,format=yuv420p10le ^
-pix_fmt yuv420p10le -f yuv4mpegpipe -strict -1 - ^
| x265-10b - --input-depth 10 -D 10 --y4m --preset medium --crf 19 --no-open-gop -I 48 ^ 
--master-display "G(8500,39850)B(6550,2300)R(35400,14600)WP(15635,16450)L(10000000,1)" --max-cll "500,400" ^
--colormatrix bt2020nc --colorprim bt2020 --transfer smpte2084 --hdr10 --hdr10-opt --repeat-headers --idr-recovery-sei ^
--range limited --vbv-bufsize 20000 --vbv-maxrate 20000 "hdr_base.hevc"
`
Then mux hdr_base.hevc into an .m2ts with TSMuxerGUI.   For this step you could also just dump it into an .mp4 with ffmpeg, but it'll spew warnings about pts not being set endlessly unless you add -loglevel error.

Then
`madmeasurehdr hdr_base.hevc` which usually takes 10-15 minutes to run on a 2 hour video and spits out a .measurements file next to it.  

Optionally use the "MadmeasureHDROptimizer" tool which you'll have to google to smooth out the target nits for the following step, or omit --use-custom-targets.

Then
`
dovi_tool generate --use-custom-targets --json generator_example.json -i hdr_base.hevc -o hdr_base.rpu
dovi_tool inject-rpu -i hdr_base.hevc -o dv8.hevc --rpu-in hdr_base.rpu
`
and finally mux dv8.hevc and any audio back into an .m2ts and feed it into your player.   

Notes:

1. The --max-cll set above is just a filler value.   The video isn't actually graded for HDR10 so an accurate value will get you something more closely approaching correct playback.  Usually the blacks will still be crushed.  DolbyVision will fix all of that.   
2. If you're pedantic or can GPU-encode HDR10 HEVC you might want to do a quick-and-dirty encode first in veryfast mode or something, run the measurements, and fill those MaxCLL and MaxFALL values in when you re-encode at high quality then run the tool again since the bad encode will have messed up light levels (but averages should be similar).
2. Pick your profile and CRF for x265 as desired.  I suggest something higher than you'd normally use because you'll be pulling shadow and highlight detail that may barely exist in the source.
3. I use .m2ts because it will play on almost anything.   FFMPEG isn't an option for muxing because it throws away DolbyVision metadata.   Another option is dolby's mp4muxer which works fine but is more limited on audio types or MKVToolNix but there's very limited support for DoVi in MKV right now.  
4. Omitting -I 48 and --no-open-gop produces non-seekable files on my LG, as the TV can't process the huge number of frames along with the dolby metadata that might be needed before a scene change occurs or if I-frames are set to their default of every 10 seconds.  Other devices might not need them.   
5. I'd expect that this CNN produces better results, I don't know.   The ghetto dolbyvision method is probably faster though unless you have a relatively current GPU, and those are selling for more than used cars.  The results of this method are more detail in highlights (and brighter blown highlight areas) and more shadow detail if the original SDR encode was good.   If it was bad or you did a CRF 22 / veryfast encode or something you'll end up with lots of noise that will be exaggerated by the DoVi. 
6. Dovi also has the side effect of converting its input via their proprietary algorithms to full range color at 12bpc which gives the set more to work with.  It's just another upscale, but it seems to make a difference regardless.  I'm not claiming it's as good as a real DV grade, but I will say the results from regular Bluray are better than at least two of the especially terrible 4k UHD graded discs I own.  YMMV, offer void in Kentucky and Missouri, supplies are limited.
