### ISSUE TITLE
Any pretrained model that could be use to evaluate？

### ISSUE THREAD

**Issue by butterl** [gabrieleilertsen/hdrcnn#7]
Hi， Is there any pretrained model that could be use to evaluate ？ I also find google‘s hdrnet  and want  to do a fast evaluation， thanks

**Comment by gabrieleilertsen** [comment]
Hi! Sorry, but I'm not sure I understand the question. There are trained parameters available (see link in the readme), together with script for running inference.

**Comment by butterl** [comment]
@gabrieleilertsen   thanks for reaching out， I success running this, I  was looking for something like checkpoint file and miss the parameters file

From the pic in data ， the detail reconstruction is wonderful for those with over exposure pictures.  For those  already in low light pictures, seem the model will make the whole picture much dark

I tried with some phone pictures from the google， the output seems not as what we expected. not sure if I missed something?
![image](https://user-images.githubusercontent.com/3068190/40873097-baa781f8-668c-11e8-8794-46a8ca2a4565.png)

**Comment by gabrieleilertsen** [comment]
Hi. It looks like the two images you show are scaled with different exposures. How have you displayed the images? Is the left the input, and right the EXR output image (xxxxxx_out.exr)? Or is the right the PNG that is also generated (xxxxxx_out.png)? The generated PNGs use reduced exposure by -3 stops, so that you easily can compare the xxxxxx_in.png and xxxxxx_out.png to assess the reconstruction without having to open the EXR image. However, these are not HDR images. The EXR store HDR reconstruction in linear values (gamma correction needed for display).

At least it looks like reconstruction works pretty well for the highlights in the right image, which would have been of lower intensity in the input image at this exposure.

Hope this helps to understand what is happening...

**Comment by butterl** [comment]
@gabrieleilertsen  Thanks for reaching out， the comparision are screen captures and the left one if the origin input image for hdrcnn model and the right one is the output. so does it mean the reconstruction is suit for those are over exposure ?   some night captured picture alway have a low average light input

**Comment by gabrieleilertsen** [comment]
If you run the reconstruction script for a certain image, you will get a folder called 'out'. This contains the reconstructed HDR image (xxxxxx_out.exr). There will also be two PNG images, xxxxxx_in.png and xxxxxx_out.png. These are not HDR, but the input image and the reconstructed HDR image displayed at a decreased exposure, in order to show differences in saturated image regions.

Night images are well-suited for the reconstruction, where it can find the intensities of light sources and the moon for example.
